### PR TITLE
[FIX] Enabled healthcat to run outside of k8s cluster

### LINKED ISSUE #51: Enable healthcat to run outside of k8s clusters
It looks like with recent changes healthcat can run in cluster only, which limits the options for a local development.

Ideally, healthcat should be able to run both in- and out of the cluster. 

See 
1. Out of cluster: https://github.com/kubernetes/client-go/tree/master/examples/out-of-cluster-client-configuration
2. In cluster: https://github.com/kubernetes/client-go/tree/master/examples/in-cluster-client-configuration

This segment 

https://github.com/wiley/healthcat/blob/master/k8s/events.go#L36-L39

should be replaced with something like this:
```
config, err := rest.InClusterConfig()
if err != nil {
    // fallback to kubeconfig
    kubeconfig := filepath.Join("~", ".kube", "config")
    if envvar := os.Getenv("KUBECONFIG"); len(envvar) >0 {
        kubeconfig = envvar
    }
    config, err = clientcmd.BuildConfigFromFlags("", kubeconfig)
    if err != nil {
        fmt.Printf("The kubeconfig cannot be loaded: %v\n", err
        os.Exit(1)
    }
}
```

### PR DESCRIPTION
**Pull request by dgeorgievski**
healthcat will fail back to out-of-cluster KUBECONFIG in case in-cluster config is not detected.
This will empower local development by eliminating the Docker build, push and deployment to k8s steps.

This resolves #51 

Test for out-of-cluster run
```
make build

$  build/bin/darwin/healthcat -i foo
[INFO] configuration file found. Loading system parameters from file config.yml
2021-08-17T17:02:42.151-0400	INFO	server/server.go:60	Starting CHC 0.2.2 on :8090
2021-08-17T17:02:42.876-0400	INFO	k8s/events.go:111	Added service: ingress-ex-fleet-ingress-ex-ingress-nginx-controller-admission.ingress-external
2021-08-17T17:02:42.876-0400	INFO	checker/checker.go:194	Adding target ingress-ex-fleet-ingress-ex-ingress-nginx-controller-admission.ingress-external
2021-08-17T17:02:42.876-0400	DEBUG	k8s/events.go:96	Ignoring service "kube-dns" in excluded namespace "kube-system"
2021-08-17T17:02:42.876-0400	INFO	k8s/events.go:111	Added service: ngx-nlb-ex-fleet-ngx-nlb-ex-ingress-nginx-controller-admission.ingress-nlb-external
2021-08-17T17:02:42.876-0400	INFO	checker/checker.go:194	Adding target ngx-nlb-ex-fleet-ngx-nlb-ex-ingress-nginx-controller-admission.ingress-nlb-external
2021-08-17T17:02:42.893-0400	INFO	checker/checker.go:251	Report from http://ngx-nlb-ex-fleet-ngx-nlb-ex-ingress-nginx-controller-admission.ingress-nlb-external:443/healthz: s:-1, h:false, err:Get "http://ngx-nlb-ex-fleet-ngx-nlb-ex-ingress-nginx-controller-admission.ingress-nlb-external:443/healthz": dial tcp: lookup ngx-nlb-ex-fleet-ngx-nlb-ex-ingress-nginx-controller-admission.ingress-nlb-external: no such host
2021-08-17T17:02:42.893-0400	INFO	checker/checker.go:251	Report from http://ingress-ex-fleet-ingress-ex-ingress-nginx-controller-admission.ingress-external:443/healthz: s:-1, h:false, err:Get "http://ingress-ex-fleet-ingress-ex-ingress-nginx-controller-admission.ingress-external:443/healthz": dial tcp: lookup ingress-ex-fleet-ingress-ex-ingress-nginx-controller-admission.ingress-external: no such host
2021-08-17T17:02:43.042-0400	INFO	k8s/events.go:111	Added service: ngx-nlb-in-fleet-ngx-nlb-in-ingress-nginx-controller-admission.ingress-nlb-internal
2021-08-17T17:02:43.042-0400	INFO	checker/checker.go:194	Adding target ngx-nlb-in-fleet-ngx-nlb-in-ingress-nginx-controller-admission.ingress-nlb-internal

....

```

### CODE REVIEW

File: k8s/events.go [hunk 1]
```diff
@@ -35,11 +38,19 @@ func (e *EventSource) Start() error {
 
 	config, err := rest.InClusterConfig()
 	if err != nil {
-		return err
+		// fallback to kubeconfig
```
Comment (axykon) [inline k8s/events.go:41]: It's better to fallback to the out-of-cluster branch only after we make sure that the error was caused by running outside of a cluster. We need something like below:
```go
config, err := rest.InClusterConfig()
if err != nil {
    if err != rest.ErrNotInCluster {
        return err
    }
    // out-of-cluster code
}	

```

File: k8s/events.go [hunk 2]
```diff
@@ -35,11 +38,19 @@ func (e *EventSource) Start() error {
...
+		kubeconfig := filepath.Join("~", ".kube", "config")
```
[the remark this answers is not in the document]
Comment (dgeorgievski) [reply k8s/events.go:42]: Good catch. I did have KUBECONFIG set while testing.

File: k8s/events.go (hunk 1 above)
Comment (dgeorgievski) [reply k8s/events.go:41]: After reviewing the InClusterConfig code  https://github.com/kubernetes/client-go/blob/v0.17.8/rest/config.go#L451 
I think this extra check, `err != rest.ErrNotInCluster`,  is not necessary.

The only other error is thrown if the function fails to read the  [k8s token](https://github.com/kubernetes/client-go/blob/v0.17.8/rest/config.go#L461).

The token error could only happen in-cluster and will be most likely resolved by a Pod restart from k8s. If the Pod keeps restarting because of the token error, then we have more serious, underlying issues to solve with the k8s cluster itself.

File: k8s/events.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (dgeorgievski) [reply k8s/events.go]: This was fixed.

File: k8s/events.go (hunk 1 above)
Comment (axykon) [reply k8s/events.go:46]: While it is totally true now, they can add more errors to the list in the future without breaking API (that is, silently). I think my suggestion just changes the condition from "if we are *maybe* running outside a cluster" to "if we are *really" running outside a cluster". The function's documentation also specifies that in case of not running in k8s env, it rerurns `ErrNotInCluster` - I consider it a hint

File: k8s/events.go [hunk 3]
```diff
@@ -57,11 +73,14 @@ func (e *EventSource) Run() {
 		return
 	}
 
+	// TODO: Confirm with Alexey if the break on line 83 was intended for the outer loop
```
Comment (axykon) [inline k8s/events.go:76]: That's a good question :). I am not sure if we should break the whole loop in case of error - that actually depends on what the error is - is it recoverable or not (I never saw these errors) and if recoverable - how should we recover from it. Seems like this particular `break` is accidental - from my Java coding habits, but I think your fix is appropriate: it's better to treat an error by default as fatal in this place until we found it is not.

**Review by axykon — APPROVED** [review]
LGTM

File: config/config.yml [hunk 4]
```diff
@@ -1,11 +1,11 @@
 # CHC configuration file
```
Comment (anlsergio) [inline config/config.yml:1]:
```suggestion
# Healthcat configuration file
```

Comment (anlsergio) [reply config/config.yml:1]: Since it's not in the scope of the proposed feature, I left this as a suggestion.

Comment (dgeorgievski) [reply config/config.yml]: I've missed it :-)
